apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: cybertech-project
build:
  artifacts:
    # Ton application Java avec Jib
    - image: cybertech-app
      jib:
        project: com.novatech.cybertech:Cybertech # Nom du projet Maven
  local:
    push: false # Ne pas pousser sur Docker Hub, utiliser le cache local

deploy:
  helm:
    releases:
      - name: cybertech-release
        chartPath: "./src/main/resources/k8s/helm/charts/cybertech-app-chart" # Chemin vers ton chart
        setValueTemplates:
          cybertechApp.image: "{{.IMAGE_FULLY_QUALIFIED_cybertech_app}}"