apiVersion: v1
kind: Service
metadata:
  name: tempo
  labels:
    app: tempo
spec:
  type: {{ .Values.service.type }}
  selector:
    app: tempo
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: otlp-grpc
      port: {{ .Values.service.otlpGrpcPort }}
      targetPort: otlp-grpc
      protocol: TCP
    - name: otlp-http
      port: {{ .Values.service.otlpHttpPort }}
      targetPort: otlp-http
      protocol: TCP
