apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              echo "Waiting for MySQL..."
              # On utilise nc (netcat) pour vérifier que le port 3306 répond
              until nc -zv {{ .Values.mysql.host }} {{ .Values.mysql.port }}; do
                sleep 2
              done
              echo "MySQL is ready!"
      containers:
        - name: keycloak
          image: {{ .Values.keycloak.image }}
          args: ["start-dev"]
          env:
            - name: KC_DB
              value: "mysql"
            - name: KC_DB_URL
              value: "jdbc:mysql://{{ .Values.mysql.host }}:{{ .Values.mysql.port }}/{{ .Values.mysql.database }}?useSSL=false&allowPublicKeyRetrieval=true"
            - name: KC_DB_USERNAME
              value: "{{ .Values.mysql.user }}"
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: db-password
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.admin.user | quote }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: admin-password
            # ... tes autres variables admin ...