apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-secret
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-username: {{ .Values.keycloak.admin.username | quote }}
  admin-password: {{ .Values.keycloak.admin.password | quote }}
  db-password: {{ .Values.keycloak.database.password | quote }}
