apiVersion: v1
kind: Service
metadata:
  name: mailpit
spec:
  selector:
    app: mailpit
  ports:
    - name: smtp
      port: {{ .Values.mailpit.smtpPort }}
      targetPort: {{ .Values.mailpit.smtpPort }}
    - name: web
      port: {{ .Values.mailpit.webPort }}
      targetPort: {{ .Values.mailpit.webPort }}
