apiVersion: v1
kind: Secret
metadata:
  name: mongodb-auth
  labels:
    app: mongodb
type: Opaque
data:
  rootUser: {{ .Values.auth.rootUser | b64enc }}
  rootPassword: {{ .Values.auth.rootPassword | b64enc }}

