{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}-auth
  labels:
    app: {{ include "mongodb.name" . }}
type: Opaque
data:
  rootUser: {{ .Values.auth.rootUser | b64enc }}
  rootPassword: {{ .Values.auth.rootPassword | b64enc }}
{{- end }}

