package com.novatech.cybertech.api.error.enumpackage;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;

@Getter
@RequiredArgsConstructor
public enum ErrorCode {

    APPLICATION_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, ErrorCodeType.TECHNICAL),
    RESOURCE_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorCodeType.TECHNICAL),
    ACCOUNT_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorCodeType.FUNCTIONAL),
    CANNOT_CANCEL_ORDER(HttpStatus.FORBIDDEN, ErrorCodeType.FUNCTIONAL),
    CANNOT_REMOVE_ITEM_FROM_EMPTY_CART(HttpStatus.FORBIDDEN, ErrorCodeType.FUNCTIONAL),
    PRODUCT_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorCodeType.FUNCTIONAL),
    ORDER_DOESNT_BELONGS_TO_USER(HttpStatus.FORBIDDEN, ErrorCodeType.FUNCTIONAL),
    FAILED_UPDATING_ORDER(HttpStatus.FORBIDDEN, ErrorCodeType.FUNCTIONAL),
    CART_IS_EMPTY(HttpStatus.FORBIDDEN, ErrorCodeType.FUNCTIONAL),
    CART_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorCodeType.FUNCTIONAL),
    CART_ITEM_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorCodeType.FUNCTIONAL),
    NO_DEFAULT_BANK_CARD_SET(HttpStatus.FORBIDDEN, ErrorCodeType.FUNCTIONAL),
    INVALID_REQUEST(HttpStatus.BAD_REQUEST, ErrorCodeType.TECHNICAL),
    MALFORMED_JSON(HttpStatus.BAD_REQUEST, ErrorCodeType.TECHNICAL),
    METHOD_ARGUMENT_TYPE_MISMATCH(HttpStatus.BAD_REQUEST, ErrorCodeType.TECHNICAL),
    ACCESS_DENIED(HttpStatus.FORBIDDEN, ErrorCodeType.FUNCTIONAL),
    ORDER_ALREADY_SHIPPED(HttpStatus.FORBIDDEN, ErrorCodeType.FUNCTIONAL),
    ORDER_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorCodeType.FUNCTIONAL),
    NO_PREVIOUS_PAYMENT_ATTEMPT_FOUND(HttpStatus.NOT_FOUND, ErrorCodeType.FUNCTIONAL),
    PRODUCT_ALREADY_IN_WISHLIST(HttpStatus.CONFLICT, ErrorCodeType.FUNCTIONAL),
    REVIEW_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorCodeType.FUNCTIONAL),
    USER_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorCodeType.FUNCTIONAL),
    USER_NOT_ACTIVE(HttpStatus.FORBIDDEN, ErrorCodeType.FUNCTIONAL),
    USER_ALREADY_EXISTS(HttpStatus.CONFLICT, ErrorCodeType.FUNCTIONAL),
    USER_NOT_AUTHOR_OF_REVIEW(HttpStatus.FORBIDDEN, ErrorCodeType.FUNCTIONAL),
    WISHLIST_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorCodeType.FUNCTIONAL),
    ACCESS_TOKEN_RETRIEVAL_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, ErrorCodeType.TECHNICAL),
    BANK_CARD_EXPIRED(HttpStatus.BAD_REQUEST, ErrorCodeType.FUNCTIONAL),
    BANK_CARD_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorCodeType.FUNCTIONAL),
    COMMENT_POST_NOT_ALLOWED(HttpStatus.FORBIDDEN, ErrorCodeType.FUNCTIONAL),
    IDEMPOTENCY_KEY_GENERATION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, ErrorCodeType.TECHNICAL),
    NO_STRATEGY_FOUND(HttpStatus.INTERNAL_SERVER_ERROR, ErrorCodeType.TECHNICAL),
    NOT_ENOUGH_STOCK(HttpStatus.CONFLICT, ErrorCodeType.FUNCTIONAL),
    ORDER_SUMMARY_REPORT_JOB_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, ErrorCodeType.TECHNICAL),
    PAYMENT_ALREADY_COMPLETED(HttpStatus.CONFLICT, ErrorCodeType.FUNCTIONAL),
    PAYMENT_FAILED(HttpStatus.PAYMENT_REQUIRED, ErrorCodeType.FUNCTIONAL),
    PAYMENT_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorCodeType.FUNCTIONAL),
    PAYMENT_PROCESSING_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, ErrorCodeType.TECHNICAL),
    DISCOUNT_TYPE_NOT_ACTIVE(HttpStatus.BAD_REQUEST, ErrorCodeType.FUNCTIONAL),
    /** BUG-161 — Authenticated user tried to read/update/delete a cart they do not own (IDOR). */
    UNAUTHORIZED_CART_ACCESS(HttpStatus.FORBIDDEN, ErrorCodeType.FUNCTIONAL);

    private final HttpStatus responseStatus;
    private final ErrorCodeType errorCodeType;
}
