replicaCount: 1

image:
  repository: hashicorp/vault
  tag: "1.18.3"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8200

storage:
  size: 2Gi

vault:
  logLevel: "info"
  clusterAddress: "http://127.0.0.1:8201"
  apiAddress: "http://vault:8200"

resources: {}