apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    app: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: {{ .Values.datasources.loki.name }}
        uid: loki
        type: loki
        access: proxy
        url: {{ .Values.datasources.loki.url | quote }}
        isDefault: {{ .Values.datasources.loki.default }}
        jsonData:
          maxLines: 1000
