services:

  mysql:
    image: mysql:9.3.0
    container_name: mysqlEcommerce
    restart: unless-stopped
    environment:
      # Vos variables existantes pour la première BDD (cybertechDB)
      # AJOUT IMPORTANT: Base de données pour Keycloak
      # L'image MySQL vous permet d'ajouter plusieurs DBs séparées par des virgules.
      # L'utilisateur 'rookie' sera automatiquement autorisé à y accéder.
      MYSQL_DATABASE: cybertechDB
      MYSQL_USER: rookie
      MYSQL_PASSWORD: pwd
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - $PWD/../sql/databaseSchemaInitFile.sql:/docker-entrypoint-initdb.d/1_databaseSchemaInitFile.sql
    healthcheck: # Ajout d'un healthcheck pour une meilleure gestion des dépendances
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - ecommerce-net

  moderation-api:
    build:
      context: ../../java/com/novatech/cybertech/api/external/moderation/
    container_name: moderation-api
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - ecommerce-net

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Interface web
    environment:
      - MP_DATA_FILE=/data/mailpit.db  # Définit le chemin de la base de données
    volumes:
      - ./mailpit-data:/data           # Crée un dossier local pour persister les emails
    networks:
      - ecommerce-net
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1025"]
      interval: 5s
      timeout: 2s
      retries: 20

  redis:
    image: 'redis:latest' # Version stable recommandée, ou specific
    container_name: redisEcommerce
    ports:
      - '6379:6379' # Ajout du mappage du port pour l'accès local
    volumes:
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      - ecommerce-net

  elasticsearch:
    image: elasticsearch:8.13.4 # Utilisez une version stable et compatible avec votre client Java
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Désactive la sécurité pour le dev local (plus simple)
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200" # Le port HTTP de l'API
    volumes:
      - esdata:/usr/share/elasticsearch/data # Persistance des données Elastic
    networks:
      - ecommerce-net
    restart: unless-stopped


  # ----------------------------------------------------
  # 5. Serveur d'Authentification : Keycloak
  # ----------------------------------------------------
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3 # Utiliser une version récente et stable
    container_name: keycloak
    environment:
      KC_DB: mysql # Le type de base de données
      KC_DB_URL: jdbc:mysql://mysql:3306/keycloakDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      KC_DB_USERNAME: rookie
      KC_DB_PASSWORD: pwd
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
      KC_HOSTNAME: localhost:8080
      KC_PROXY_HEADERS: xforwarded
      KC_PROXY: edge

    ports:
      - "8080:8080"
    command: start-dev # Mode de démarrage développement
    networks:
      - ecommerce-net
    depends_on:
      - mysql
#        condition: service_healthy # Attend que MySQL soit prêt
    restart: unless-stopped


volumes:
  mysql_data:
    driver: local
  esdata:
    driver: local

networks:
  ecommerce-net:
    driver: bridge



#  kafka:
#    image: apache/kafka:3.7.0 # Je te conseille de rester sur la 3.7/3.8, la 4.x est très récente
#    container_name: kafka
#    ports:
#      - "9092:9092"
#    environment:
#      - KAFKA_NODE_ID=1
#      - KAFKA_PROCESS_ROLES=broker,controller
#      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
#
#      # On définit 3 noms de protocoles
#      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
#
#      # On écoute sur 3 ports différents
#      # 9092: Externe (Windows)
#      # 9094: Interne (Docker)
#      # 9093: Contrôleur KRaft
#      - KAFKA_LISTENERS=EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093
#
#      # C'est ici que la magie opère :
#      # Si on vient de l'extérieur, on s'adresse à localhost:9092
#      # Si on vient de l'intérieur (Docker), on s'adresse à kafka:9094
#      - KAFKA_ADVERTISED_LISTENERS=EXTERNAL://localhost:9092,INTERNAL://kafka:9094
#
#      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
#      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
#      - KAFKA_LOG_DIRS=/var/lib/kafka/data
#      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
#    networks:
#      - ecommerce-net
#
#  kafka-ui:
#    image: provectuslabs/kafka-ui:latest
#    container_name: kafka-ui
#    ports:
#      - "8090:8080"  # <--- On change ici : 8090 sur Windows pointera vers 8080 dans Docker
#    environment:
#      - KAFKA_CLUSTERS_0_NAME=local
#      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9094
#    networks:
#      - ecommerce-net
#    depends_on:
#      - kafka