apiVersion: v1
kind: Secret
metadata:
  name: localstack-secret
  labels:
    app: localstack
type: Opaque
stringData:
  aws-access-key-id: {{ .Values.credentials.accessKeyId | quote }}
  aws-secret-access-key: {{ .Values.credentials.secretAccessKey | quote }}

