apiVersion: v1
kind: Service
metadata:
  name: moderation-api
spec:
  selector:
    app: moderation-api
  ports:
    - port: {{ .Values.moderationApi.port }}
      targetPort: {{ .Values.moderationApi.port }}
