mysql:
  image: mysql:9.3.0
  port: 3306

  rootPassword: ""
  user: rookie
  password: pwd
  database: cybertechDB

  persistence:
    enabled: true
    size: 5Gi
    # IMPORTANT: StatefulSet crée 1 PVC par replica via volumeClaimTemplates
    # Ne pas créer de PVC séparé

service:
  type: ClusterIP
  #::::clusterIP: None  # Headless service for StatefulSet DNS

initSql:
  enabled: true
  filename: databaseSchemaInitFile.sql
