apiVersion: v1
kind: Service
metadata:
  name: stripe
  labels:
    app: stripe
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: stripe
  selector:
    app: stripe

